---
web:
    site1:
        hosts:
            - web1
            - web2
        vars:
            - testvar: myvalue
    site2:
        hosts:
            - web3
            - web4
db:
    site1:
        hosts:
            - db1
            - db2
    site2:
        hosts:
            - db3
            - db4